set(ARDUINO_UNO_PROTOCOL "arduino")
set(ARDUINO_UNO_BOARD "standard")
set(ARDUINO_UNO_MCU "atmega328p")
set(ARDUINO_UNO_FCPU "16000000")
set(ARDUINO_UNO_UPLOAD_SPEED "115200")
set(ARDUINO_UNO_PORT "/dev/ttyACM1")
set(ARDUINO_UNO_ROOT "$ENV{HOME}/opt/arduino")
set(CMAKE_C_COMPILER "${ARDUINO_UNO_ROOT}/hardware/tools/avr/bin/avr-gcc")
set(CMAKE_CXX_COMPILER "${ARDUINO_UNO_ROOT}/hardware/tools/avr/bin/avr-g++")
set(ARDUINO_UNO_OBJCOPY "${ARDUINO_UNO_ROOT}/hardware/tools/avr/bin/avr-objcopy")
set(ARDUINO_UNO_AVRDUDE "${ARDUINO_UNO_ROOT}/hardware/tools/avr/bin/avrdude")
include(${CMAKE_SOURCE_DIR}/scripts/libarduino_uno.cmake)